### ISSUE TITLE
Launch  the LLM locally

### ISSUE THREAD

**Issue by LarryBattle** [LarryBattle/DocuDive#12]

**Comment by doubleope** [comment]
Was able to run the models locally but performance was very low for the larger model: https://github.com/LarryBattle/DocuDive/tree/main/v1.0_loading_llm_model/peter_history_june_15_2023

**Comment by LarryBattle** [comment]
This is done.
.env used

```
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=../v1.0_llm_models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
MODEL_N_BATCH=8
TARGET_SOURCE_CHUNKS=4
SOURCE_DIRECTORY=web/static/v1.0_fake_products
```
file: https://github.com/LarryBattle/DocuDive/blob/main/v1.1_microservice/example.env
