### ISSUE TITLE
Launch the LLM in AWS

### ISSUE THREAD

**Issue by LarryBattle** [LarryBattle/DocuDive#13]

**Comment by LarryBattle** [comment]
In progress. 
We're using a modified version of PrivateGPT for the LLM/VectorStore
Problem: we're having a problem with accessing the public ips for the EC2 instance. I'll update the security groups shortly.

**Comment by doubleope** [comment]
I'm working on that

**Comment by doubleope** [comment]
almost done

**Comment by doubleope** [comment]
hey Larry are you working on the instance?

**Comment by LarryBattle** [comment]
Yeah, sorry about that. I did a restart 20 mins ago because I couldn't relaunch it

**Comment by LarryBattle** [comment]
Found the issue with why the app wasn't up and running. Working on pushing the changes

In app.py, don't listen on `localhost` but `0.0.0.0` and make sure the service startups

**Comment by LarryBattle** [comment]
Done. And launched it to a new EC2 instance.
Change here.
https://github.com/LarryBattle/DocuDive/pull/27
