### ISSUE TITLE
Create a microservice to use for the LLM / VectorStore

### ISSUE THREAD

**Issue by LarryBattle** [LarryBattle/DocuDive#19]

**Comment by LarryBattle** [comment]
@brayanpena530 Please move all the code to https://github.com/LarryBattle/DocuDive/blob/main/v1.1_microservice/
I see code at the root of this directory

Also please add readme.md and instructions on how to setup

This might be helpful:
## To download models run
wget https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin
wget https://huggingface.co/eachadea/ggml-nous-hermes-13b/resolve/main/ggml-v3-13b-hermes-q5_1.bin

**Comment by LarryBattle** [comment]
Related issue: https://github.com/LarryBattle/DocuDive/issues/2

**Comment by LarryBattle** [comment]
@brayanpena530 Can you output the timeformat in this 

```python
>>> datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
'2018-09-05T14:09:03Z'
```

**Comment by brayanpena530** [comment]
sure thing

**Comment by LarryBattle** [comment]
I moved the code in this PR and made the API match the /keepalive and /api/ask endpoints
Changes here: https://github.com/LarryBattle/DocuDive/pull/27
