### ISSUE TITLE
Create the architecture and API contracts for each main modules

### ISSUE THREAD

**Issue by LarryBattle** [LarryBattle/DocuDive#2]
## Architecture

LLM Server (Platformat: AWS or local)
OS: Linux OS, Windows 10/11

### Components
- RAW Documents DB / Folder
- Saved VectorStore DB / Folder
- Redis or InMemory DB for DocuDive LLM Service

- PrivateGPT?: Uses the VectorStore and LLM to handle the query and generated the responses
- DocuDive LLM Service - exposes PrivateGPT as a microservice
- DocuDive UI Service - allows the user to query PrivateGPT

## APIs
endpoints:
- GET http://dive-service/api/keepalive -> JSON 
returns { up: true }
This page returns static content just to check that the service is up and running
- POST http://dive-service/api/query -> JSON
    - request: 
    ```js
    {
        userQuery: ""
    }
    ```
    - returns 200 if able to create a job and 
        * JSON format

        ```js
        {
            responseId: "",
            timestamp: string, // UTC string
            completionTimeStamp: string // UTC string
        }
        ```

- GET http://dive-service/api/query/${query_response} -> JSON
    - returns 404 if query response isn't found in the DB
        * no response / only HTTP status code
    - returns 202 for the create query response was created but pending a LLM response
        * no response / only HTTP status code
    - returns 200 for when the query response is completed a LLM response is provided.
        * response format
            
            ```js
            { 
                result : string, 
                timestamp: string // UTC timestamp,
                isSuccess: boolean,
                jobDurationSeconds : Integer // how many seconds it took to complete the job 
            }
            ```

## UI:
- GET http://ui-service/keepalive
return { "up": true }
This page returns static content just to check that the service is up and running

- GET http://ui-service/
returns UI

UI Components:
- Explaination of project
- Link to github
- input to submit query: 
- submit button:
- output to show response:
- loading status:
- DocuDive server status:

**Comment by LarryBattle** [comment]
User -> UI
UI -> DocuDive Service

DocuDive Service -> CacheDB (InMemory or Redis)
DocuDive Service -> VectorStoreDB

UpdateVectorStoreDB CronJob -> Raw Documents
UpdateVectorStoreDB CronJob -> VectorStoreDB

**Comment by LarryBattle** [comment]
@alxschlz98 Can you use this for your UI?


- POST http://dive-service/api/ask -> JSON
    - request:
    ```
    {
        query : "" // string
    }
    ```
    - returns 200 if able to create a job and 
        * JSON format
```js
{ 
    result : LLM_RESPONSE, 
    timestamp: string // UTC timestamp,
    isSuccess: boolean,
    jobDurationSeconds : Integer // how many seconds it took to complete the job 
}
```

**Comment by brayanpena530** [comment]
JSON schema for LLM_RESPONSE
```js
{
    "answer": String,
    "Documents": {
        "${DOCUMENT_REFERENCE_LINK}": String // citation
    }
}
```

Example output

```js
{
    "answer": " The context does not provide an answer to this question as it deals with Russia's actions, rather than a specific statement made by President Zelenskyy or any other person mentioned in the text.",
    "Documents": {
        "source_documents\\state_of_the_union.txt": "The United States is a member along with 29 other nations. \n\nIt matters. American diplomacy matters. American resolve matters. \n\nPutin’s latest attack on Ukraine was premeditated and unprovoked. \n\nHe rejected repeated efforts at diplomacy. \n\nHe thought the West and NATO wouldn’t respond. And he thought he could divide us at home. Putin was wrong. We were ready.  Here is what we did.   \n\nWe prepared extensively and carefully."
    }
}
```

**Comment by alxschlz98** [comment]
> @alxschlz98 Can you use this for your UI?
> 
>     * POST http://dive-service/api/ask -> JSON
>       
>       * request:
>       
>       ```
>       {
>           query : "" // string
>       }
>       ```
>       
>       * returns 200 if able to create a job and
>         
>         * JSON format
> 
> ```js
> { 
>     result : LLM_RESPONSE, 
>     timestamp: string // UTC timestamp,
>     isSuccess: boolean,
>     jobDurationSeconds : Integer // how many seconds it took to complete the job 
> }
> ```

Will do, are there two endpoints that need to be hit? Or should the request keep hitting with the same prompt?

**Comment by brayanpena530** [comment]
Here is a full sample response: 

```js
{
    "result": {
        "answer": " Connectifiy, also known as CN or SeaMless Connectivity for All Your Devices! Is a versatile software solution that transforms your computer into a powerful virtual router. It enables seamless internet connectivity and network sharing by enabling hotspot creation (HS), management of networks with intuitive interface, the ability to share access through collaboration features (CollaboraTiON w/ ISPs).",
        "Documents": {
            "v1.0_fake_products\\connectify.txt": "Key Activities:\n- Continuous improvement and feature updates of Connectify (UPD)\n- Gathering user feedback for product enhancements (FB)\n- Providing comprehensive training and customer support (TS)\n\nValue Propositions:\n- Transform your computer into a virtual router with a simple interface (UI)\n- Share internet connections with other devices seamlessly (HS)\n- Ensure data security and privacy with advanced encryption (AS)"
        }
    },
    "timestamp": "15/06/2023 16:12:39",
    "isSuccess": true,
    "jobDurationSeconds": 109.0
}
```

**Comment by LarryBattle** [comment]
@alxschlz98 No, it's just 1 endpoint that you'll send the query too and wait for a response. It'll take anywhere from 60s to 600s to complete, so please include a loader in the UI

**Comment by LarryBattle** [comment]
Related ticket with additional information https://github.com/LarryBattle/DocuDive/issues/6
